### ISSUE TITLE
Embeddings for my dataset

### ISSUE THREAD

**Issue by brunoaibanez** [D2KLab/Face-Celebrity-Recognition#17]
I was running the code on my own dataset. Do I have to get the embeddings myself? How do I get them with the scripts you guys provide? When running the download and then running the SVM training, it raises the following error:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/embedding/project.csv'`

**Comment by rtroncy** [comment]
Did you find out how to resolve your problem?

**Comment by pasqLisena** [comment]
Hi Bruno, can you please try to create the `data/embedding/` folder manually?

-----
If I well understand, you don't want to use image crawled from the web.

In that case, you should:
- load your images in `data/training_img/project`
- run `python -m src.FaceDetector project`
- then continue according to the documentation :)

**Comment by brunoaibanez** [comment]
Hello guys,
I closed the issue before because I tried what @pasqLisena said and it worked. You might want to add it on the documentation. 

I also found the following issue:

`AttributeError: Can't get attribute 'FacerecClassifier' on <module 'src.tracker' from '/content/Face-Celebrity-Recognition/src/tracker.py'>`

I solved it by importing on tracker.py:
`from .classifier import FacerecClassifier`

**Comment by brunoaibanez** [comment]
Now, I finally have the predictions.csv and trackers.csv, do you guys have any script to visualize on the video the predictions? Just like painting the different bounding boxes on the video? In case not, and knowing that I will have to write it anyways, I will fork the repo and create one.

**Comment by rtroncy** [comment]
There is a visualized app in the repo. You can experience it at http://facerec.eurecom.fr/visualizer/
